//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int AppointmentId { get; set; }
        public int UserId { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> PrefectId { get; set; }
        public string Reason { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> CancellationReasonId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual CancellationReasons CancellationReasons { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Prefects Prefects { get; set; }
    }
}
